function fetchTainanBusNetwork() {
  const network = {
    data: {
      VersionID: 8527,
      UpdateTime: "2025-12-18T00:00:00+08:00",
      UpdateInterval: 14400,
      SrcUpdateTime: "2025-12-18T01:05:00+08:00",
      SrcUpdateInterval: 86400,
      AuthorityCode: "TNN",
      Networks: [
        {
          NetworkID: "TNN-Network",
          NetworkName: {
            Zh_tw: "臺南市公車營運路網",
            En: "Tainan Bus Operation Network",
          },
          NetworkMapURL: {
            MapName: "臺南市公車路網圖",
            MapNameURL: {
              Zh_tw:
                "http://traffic.tainan.gov.tw/Uploads/Tainan_Bus_Route_Map_4_Urban_6MB.jpg",
              En: "http://traffic.tainan.gov.tw/Uploads/Tainan_Bus_Route_Map_4_Urban_6MB.jpg",
            },
          },
          LBSMapURLs: [],
        },
      ],
    },
    status: 200,
    statusText: "",
    headers: {
      "content-length": "371",
      "content-type": "application/json; charset=utf-8",
      "last-modified": "Wed, 17 Dec 2025 16:00:00 GMT",
    },
    config: {
      transitional: {
        silentJSONParsing: true,
        forcedJSONParsing: true,
        clarifyTimeoutError: false,
      },
      adapter: ["xhr", "http", "fetch"],
      transformRequest: [null],
      transformResponse: [null],
      timeout: 0,
      xsrfCookieName: "XSRF-TOKEN",
      xsrfHeaderName: "X-XSRF-TOKEN",
      maxContentLength: -1,
      maxBodyLength: -1,
      env: {},
      headers: {
        Accept: "application/json, text/plain, */*",
        Authorization:
          'hmac username="FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF", algorithm="hmac-sha1", headers="x-date", signature="tEd6g64S8HDA0IXI/qWaaNs8Zo4="',
        "X-Date": "Thu, 18 Dec 2025 06:51:36 GMT",
      },
      method: "get",
      url: "https://tdx.transportdata.tw/api/basic/v3/Bus/Network/City/Tainan?%24top=30&%24format=JSON",
      allowAbsoluteUrls: true,
    },
    request: "[object XMLHttpRequest]",
  };

  const realTimeNearStop = [
    {
      PlateNumb: "648-FS",
      OperatorID: "10160",
      OperatorNo: "1601",
      RouteUID: "TNN1201",
      RouteID: "1201",
      RouteName: {
        Zh_tw: "藍1",
        En: "B1",
      },
      SubRouteUID: "TNN120102",
      SubRouteID: "120102",
      SubRouteName: {
        Zh_tw: "藍1 南鯤鯓→西埔內→苓子寮→佳里",
        En: "B1 Nankunshen Temple→Jiali Bus Station",
      },
      Direction: 1,
      StopUID: "TNN5843",
      StopID: "5843",
      StopName: {
        Zh_tw: "苓子寮",
        En: "Lingzihliao",
      },
      StopSequence: 16,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 0,
      A2EventType: 1,
      GPSTime: "2025-12-18T16:13:29+08:00",
      TripStartTimeType: 0,
      TripStartTime: "2025-12-18T15:50:05+08:00",
      TransTime: "2025-12-18T16:13:29+08:00",
      SrcRecTime: "2025-12-18T16:13:29+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "661-FS",
      OperatorID: "10160",
      OperatorNo: "1601",
      RouteUID: "TNN1211",
      RouteID: "1211",
      RouteName: {
        Zh_tw: "藍11",
        En: "B11",
      },
      SubRouteUID: "TNN121102",
      SubRouteID: "121102",
      SubRouteName: {
        Zh_tw: "藍11 青鯤鯓→城子內→佳里",
        En: "B11 Kunsheng Harbor→Jiali Bus Station",
      },
      Direction: 1,
      StopUID: "TNN6035",
      StopID: "6035",
      StopName: {
        Zh_tw: "佳里站",
        En: "Jiali Bus Station",
      },
      StopSequence: 17,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 0,
      A2EventType: 0,
      GPSTime: "2025-12-18T16:00:40+08:00",
      TripStartTimeType: 0,
      TripStartTime: "2025-12-18T15:39:42+08:00",
      TransTime: "2025-12-18T16:00:40+08:00",
      SrcRecTime: "2025-12-18T16:00:40+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "663-FS",
      OperatorID: "10160",
      OperatorNo: "1601",
      RouteUID: "TNN1220",
      RouteID: "1220",
      RouteName: {
        Zh_tw: "藍20",
        En: "B20",
      },
      SubRouteUID: "TNN122002",
      SubRouteID: "122002",
      SubRouteName: {
        Zh_tw: "藍20 馬沙溝遊憩區→青鯤鯓→台區→佳里",
        En: "B20 Mashagou Recreation Area→Jiali Bus Station",
      },
      Direction: 1,
      StopUID: "TNN6146",
      StopID: "6146",
      StopName: {
        Zh_tw: "三合",
        En: "Sanhe",
      },
      StopSequence: 24,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 0,
      A2EventType: 1,
      GPSTime: "2025-12-18T16:13:51+08:00",
      TripStartTimeType: 0,
      TripStartTime: "2025-12-18T15:40:32+08:00",
      TransTime: "2025-12-18T16:13:51+08:00",
      SrcRecTime: "2025-12-18T16:13:51+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "683-FS",
      OperatorID: "10160",
      OperatorNo: "1601",
      RouteUID: "TNN1202",
      RouteID: "1202",
      RouteName: {
        Zh_tw: "藍2",
        En: "B2",
      },
      SubRouteUID: "TNN120211",
      SubRouteID: "120211",
      SubRouteName: {
        Zh_tw: "藍2 佳里→溪底寮→南鯤鯓(不經井仔腳)",
        En: "B2 Jiali Bus Station→Nankunshen Temple[Non-Via Jingzihjiao]",
      },
      Direction: 0,
      StopUID: "TNN5864",
      StopID: "5864",
      StopName: {
        Zh_tw: "學甲市場",
        En: "Syuejia Market",
      },
      StopSequence: 17,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 0,
      A2EventType: 0,
      GPSTime: "2025-12-18T16:13:26+08:00",
      TripStartTimeType: 0,
      TripStartTime: "2025-12-18T15:51:44+08:00",
      TransTime: "2025-12-18T16:13:28+08:00",
      SrcRecTime: "2025-12-18T16:13:28+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "EAA-797",
      OperatorID: "10160",
      OperatorNo: "1601",
      RouteUID: "TNN1200",
      RouteID: "1200",
      RouteName: {
        Zh_tw: "藍幹線",
        En: "Blue",
      },
      SubRouteUID: "TNN120002",
      SubRouteID: "120002",
      SubRouteName: {
        Zh_tw: "藍幹線 佳里→安平工業區",
        En: "Blue Jiali Bus Station→Anping Industrial Park",
      },
      Direction: 1,
      StopUID: "TNN5785",
      StopID: "5785",
      StopName: {
        Zh_tw: "六甲頂",
        En: "Lioujiading",
      },
      StopSequence: 29,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 0,
      A2EventType: 1,
      GPSTime: "2025-12-18T16:13:03+08:00",
      TripStartTimeType: 0,
      TripStartTime: "2025-12-18T15:30:06+08:00",
      TransTime: "2025-12-18T16:13:03+08:00",
      SrcRecTime: "2025-12-18T16:13:03+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "EAA-798",
      OperatorID: "10160",
      OperatorNo: "1601",
      RouteUID: "TNN1200",
      RouteID: "1200",
      RouteName: {
        Zh_tw: "藍幹線",
        En: "Blue",
      },
      SubRouteUID: "TNN120001",
      SubRouteID: "120001",
      SubRouteName: {
        Zh_tw: "藍幹線 安平工業區→佳里",
        En: "Blue Anping Industrial Park→Jiali Bus Station",
      },
      Direction: 0,
      StopUID: "TNN5746",
      StopID: "5746",
      StopName: {
        Zh_tw: "北和順",
        En: "North Heshun",
      },
      StopSequence: 35,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 0,
      A2EventType: 0,
      GPSTime: "2025-12-18T16:13:12+08:00",
      TripStartTimeType: 0,
      TripStartTime: "2025-12-18T15:14:58+08:00",
      TransTime: "2025-12-18T16:13:13+08:00",
      SrcRecTime: "2025-12-18T16:13:13+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "EAL-2301",
      OperatorID: "10160",
      OperatorNo: "1601",
      RouteUID: "TNN1200",
      RouteID: "1200",
      RouteName: {
        Zh_tw: "藍幹線",
        En: "Blue",
      },
      SubRouteUID: "TNN120002",
      SubRouteID: "120002",
      SubRouteName: {
        Zh_tw: "藍幹線 佳里→安平工業區",
        En: "Blue Jiali Bus Station→Anping Industrial Park",
      },
      Direction: 1,
      StopUID: "TNN5796",
      StopID: "5796",
      StopName: {
        Zh_tw: "小西門(府前路)",
        En: "Siaosimen(FuCian Rd.)",
      },
      StopSequence: 41,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 0,
      A2EventType: 0,
      GPSTime: "2025-12-18T16:13:37+08:00",
      TripStartTimeType: 0,
      TripStartTime: "2025-12-18T15:00:31+08:00",
      TransTime: "2025-12-18T16:13:36+08:00",
      SrcRecTime: "2025-12-18T16:13:36+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "EAL-2303",
      OperatorID: "10160",
      OperatorNo: "1601",
      RouteUID: "TNN1200",
      RouteID: "1200",
      RouteName: {
        Zh_tw: "藍幹線",
        En: "Blue",
      },
      SubRouteUID: "TNN120001",
      SubRouteID: "120001",
      SubRouteName: {
        Zh_tw: "藍幹線 安平工業區→佳里",
        En: "Blue Anping Industrial Park→Jiali Bus Station",
      },
      Direction: 0,
      StopUID: "TNN5722",
      StopID: "5722",
      StopName: {
        Zh_tw: "水萍塭公園",
        En: "Shueipingwun Park",
      },
      StopSequence: 7,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 0,
      A2EventType: 0,
      GPSTime: "2025-12-18T16:14:03+08:00",
      TripStartTimeType: 0,
      TripStartTime: "2025-12-18T16:01:22+08:00",
      TransTime: "2025-12-18T16:14:03+08:00",
      SrcRecTime: "2025-12-18T16:14:03+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "EAL-2305",
      OperatorID: "10160",
      OperatorNo: "1601",
      RouteUID: "TNN1200",
      RouteID: "1200",
      RouteName: {
        Zh_tw: "藍幹線",
        En: "Blue",
      },
      SubRouteUID: "TNN120002",
      SubRouteID: "120002",
      SubRouteName: {
        Zh_tw: "藍幹線 佳里→安平工業區",
        En: "Blue Jiali Bus Station→Anping Industrial Park",
      },
      Direction: 1,
      StopUID: "TNN5790",
      StopID: "5790",
      StopName: {
        Zh_tw: "臺南轉運站",
        En: "Tainan Bus Station",
      },
      StopSequence: 34,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 0,
      A2EventType: 1,
      GPSTime: "2025-12-18T16:13:01+08:00",
      TripStartTimeType: 0,
      TripStartTime: "2025-12-18T15:16:25+08:00",
      TransTime: "2025-12-18T16:13:01+08:00",
      SrcRecTime: "2025-12-18T16:13:01+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "EAL-2306",
      OperatorID: "10160",
      OperatorNo: "1601",
      RouteUID: "TNN1200",
      RouteID: "1200",
      RouteName: {
        Zh_tw: "藍幹線",
        En: "Blue",
      },
      SubRouteUID: "TNN120001",
      SubRouteID: "120001",
      SubRouteName: {
        Zh_tw: "藍幹線 安平工業區→佳里",
        En: "Blue Anping Industrial Park→Jiali Bus Station",
      },
      Direction: 0,
      StopUID: "TNN5716",
      StopID: "5716",
      StopName: {
        Zh_tw: "安平工業區",
        En: "Anping Industrial Park",
      },
      StopSequence: 1,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 0,
      A2EventType: 1,
      GPSTime: "2025-12-18T16:14:00+08:00",
      TripStartTimeType: 0,
      TripStartTime: "2025-12-18T16:14:00+08:00",
      TransTime: "2025-12-18T16:13:59+08:00",
      SrcRecTime: "2025-12-18T16:13:59+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "EAL-2309",
      OperatorID: "10160",
      OperatorNo: "1601",
      RouteUID: "TNN1200",
      RouteID: "1200",
      RouteName: {
        Zh_tw: "藍幹線",
        En: "Blue",
      },
      SubRouteUID: "TNN120001",
      SubRouteID: "120001",
      SubRouteName: {
        Zh_tw: "藍幹線 安平工業區→佳里",
        En: "Blue Anping Industrial Park→Jiali Bus Station",
      },
      Direction: 0,
      StopUID: "TNN5738",
      StopID: "5738",
      StopName: {
        Zh_tw: "安順",
        En: "Anshun",
      },
      StopSequence: 24,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 0,
      A2EventType: 1,
      GPSTime: "2025-12-18T16:13:27+08:00",
      TripStartTimeType: 0,
      TripStartTime: "2025-12-18T15:29:44+08:00",
      TransTime: "2025-12-18T16:13:28+08:00",
      SrcRecTime: "2025-12-18T16:13:28+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "EAL-2315",
      OperatorID: "10160",
      OperatorNo: "1601",
      RouteUID: "TNN1200",
      RouteID: "1200",
      RouteName: {
        Zh_tw: "藍幹線",
        En: "Blue",
      },
      SubRouteUID: "TNN120001",
      SubRouteID: "120001",
      SubRouteName: {
        Zh_tw: "藍幹線 安平工業區→佳里",
        En: "Blue Anping Industrial Park→Jiali Bus Station",
      },
      Direction: 0,
      StopUID: "TNN5754",
      StopID: "5754",
      StopName: {
        Zh_tw: "北西港",
        En: "North Sigang",
      },
      StopSequence: 43,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 0,
      A2EventType: 1,
      GPSTime: "2025-12-18T16:14:03+08:00",
      TripStartTimeType: 1,
      TripStartTime: "2025-12-18T14:58:42+08:00",
      TransTime: "2025-12-18T16:14:03+08:00",
      SrcRecTime: "2025-12-18T16:14:03+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "EAL-2317",
      OperatorID: "10160",
      OperatorNo: "1601",
      RouteUID: "TNN1200",
      RouteID: "1200",
      RouteName: {
        Zh_tw: "藍幹線",
        En: "Blue",
      },
      SubRouteUID: "TNN120002",
      SubRouteID: "120002",
      SubRouteName: {
        Zh_tw: "藍幹線 佳里→安平工業區",
        En: "Blue Jiali Bus Station→Anping Industrial Park",
      },
      Direction: 1,
      StopUID: "TNN5766",
      StopID: "5766",
      StopName: {
        Zh_tw: "北西港",
        En: "North Sigang",
      },
      StopSequence: 7,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 0,
      A2EventType: 0,
      GPSTime: "2025-12-18T16:13:57+08:00",
      TripStartTimeType: 0,
      TripStartTime: "2025-12-18T16:00:30+08:00",
      TransTime: "2025-12-18T16:13:58+08:00",
      SrcRecTime: "2025-12-18T16:13:58+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "EAL-2318",
      OperatorID: "10160",
      OperatorNo: "1601",
      RouteUID: "TNN1210",
      RouteID: "1210",
      RouteName: {
        Zh_tw: "藍10",
        En: "B10",
      },
      SubRouteUID: "TNN121001",
      SubRouteID: "121001",
      SubRouteName: {
        Zh_tw: "藍10 佳里→馬沙溝→將軍漁港",
        En: "B10 Jiali Bus Station→Jiangjyun Fish Port",
      },
      Direction: 0,
      StopUID: "TNN5960",
      StopID: "5960",
      StopName: {
        Zh_tw: "潭墘",
        En: "Tancian",
      },
      StopSequence: 3,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 0,
      A2EventType: 1,
      GPSTime: "2025-12-18T16:13:07+08:00",
      TripStartTimeType: 0,
      TripStartTime: "2025-12-18T16:10:52+08:00",
      TransTime: "2025-12-18T16:13:07+08:00",
      SrcRecTime: "2025-12-18T16:13:07+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "EAL-2320",
      OperatorID: "10160",
      OperatorNo: "1601",
      RouteUID: "TNN1210",
      RouteID: "1210",
      RouteName: {
        Zh_tw: "藍10",
        En: "B10",
      },
      SubRouteUID: "TNN121002",
      SubRouteID: "121002",
      SubRouteName: {
        Zh_tw: "藍10 將軍漁港→馬沙溝→佳里",
        En: "B10 Jiangjyun Fish Port→Jiali Bus Station",
      },
      Direction: 1,
      StopUID: "TNN5997",
      StopID: "5997",
      StopName: {
        Zh_tw: "竹子腳",
        En: "Jhuzihjiao",
      },
      StopSequence: 21,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 0,
      A2EventType: 0,
      GPSTime: "2025-12-18T16:13:00+08:00",
      TripStartTimeType: 0,
      TripStartTime: "2025-12-18T15:51:02+08:00",
      TransTime: "2025-12-18T16:13:00+08:00",
      SrcRecTime: "2025-12-18T16:13:00+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "EAL-2321",
      OperatorID: "10160",
      OperatorNo: "1601",
      RouteUID: "TNN1220",
      RouteID: "1220",
      RouteName: {
        Zh_tw: "藍20",
        En: "B20",
      },
      SubRouteUID: "TNN122001",
      SubRouteID: "122001",
      SubRouteName: {
        Zh_tw: "藍20 佳里→台區→青鯤鯓→馬沙溝遊憩區",
        En: "B20 Jiali Bus Station→Mashagou Recreation Area",
      },
      Direction: 0,
      StopUID: "TNN6123",
      StopID: "6123",
      StopName: {
        Zh_tw: "青山漁港",
        En: "Cingshan  Fish Port",
      },
      StopSequence: 26,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 0,
      A2EventType: 1,
      GPSTime: "2025-12-18T16:13:57+08:00",
      TripStartTimeType: 0,
      TripStartTime: "2025-12-18T15:40:25+08:00",
      TransTime: "2025-12-18T16:13:58+08:00",
      SrcRecTime: "2025-12-18T16:13:58+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "EAL-2322",
      OperatorID: "10160",
      OperatorNo: "1601",
      RouteUID: "TNN1213",
      RouteID: "1213",
      RouteName: {
        Zh_tw: "藍13",
        En: "B13",
      },
      SubRouteUID: "TNN121301",
      SubRouteID: "121301",
      SubRouteName: {
        Zh_tw: "藍13 佳里→西寮",
        En: "B13 Jiali Bus Station→Siliao",
      },
      Direction: 0,
      StopUID: "TNN6082",
      StopID: "6082",
      StopName: {
        Zh_tw: "五棟寮",
        En: "Wudongliao",
      },
      StopSequence: 13,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 0,
      A2EventType: 0,
      GPSTime: "2025-12-18T16:13:05+08:00",
      TripStartTimeType: 0,
      TripStartTime: "2025-12-18T16:00:39+08:00",
      TransTime: "2025-12-18T16:13:05+08:00",
      SrcRecTime: "2025-12-18T16:13:05+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "KKA-7305",
      OperatorID: "10160",
      OperatorNo: "1601",
      RouteUID: "TNN1224",
      RouteID: "1224",
      RouteName: {
        Zh_tw: "藍24",
        En: "B24",
      },
      SubRouteUID: "TNN122402",
      SubRouteID: "122402",
      SubRouteName: {
        Zh_tw: "藍24 青草里→土城子→安平工業區",
        En: "B24 Cingcao Vil.→Anping Industrial Park",
      },
      Direction: 1,
      StopUID: "TNN6419",
      StopID: "6419",
      StopName: {
        Zh_tw: "中華社區",
        En: "Jhonghua Community",
      },
      StopSequence: 32,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 0,
      A2EventType: 0,
      GPSTime: "2025-12-18T16:13:57+08:00",
      TripStartTimeType: 0,
      TripStartTime: "2025-12-18T15:40:15+08:00",
      TransTime: "2025-12-18T16:13:58+08:00",
      SrcRecTime: "2025-12-18T16:13:58+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "KKA-7306",
      OperatorID: "10160",
      OperatorNo: "1601",
      RouteUID: "TNN1223",
      RouteID: "1223",
      RouteName: {
        Zh_tw: "藍23",
        En: "B23",
      },
      SubRouteUID: "TNN122301",
      SubRouteID: "122301",
      SubRouteName: {
        Zh_tw: "藍23 安平工業區→九塊厝",
        En: "B23 Anping Industrial Park→Jioukuaicuo",
      },
      Direction: 0,
      StopUID: "TNN6293",
      StopID: "6293",
      StopName: {
        Zh_tw: "三股",
        En: "Sangu",
      },
      StopSequence: 44,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 0,
      A2EventType: 0,
      GPSTime: "2025-12-18T16:06:30+08:00",
      TripStartTimeType: 0,
      TripStartTime: "2025-12-18T15:01:26+08:00",
      TransTime: "2025-12-18T16:06:31+08:00",
      SrcRecTime: "2025-12-18T16:06:31+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "TDQ-9756",
      OperatorID: "16202",
      OperatorNo: "",
      RouteUID: "TNN1214",
      RouteID: "1214",
      RouteName: {
        Zh_tw: "藍14",
        En: "B14",
      },
      SubRouteUID: "TNN121402",
      SubRouteID: "121402",
      SubRouteName: {
        Zh_tw: "藍14 奇美佳里分院→學甲區公所",
        En: "B14 Chi Mei Jiali Hospital→Syuejia District Office",
      },
      Direction: 1,
      StopUID: "TNN24767",
      StopID: "24767",
      StopName: {
        Zh_tw: "巷埔里(北埔)",
        En: "Siangpu Vil.(Beipu)",
      },
      StopSequence: 12,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 99,
      A2EventType: 0,
      GPSTime: "2025-12-18T16:06:15+08:00",
      TripStartTimeType: 0,
      TripStartTime: "2025-12-18T15:42:51+08:00",
      TransTime: "2025-12-18T16:06:17+08:00",
      SrcRecTime: "2025-12-18T16:06:17+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "TDT-6130",
      OperatorID: "16202",
      OperatorNo: "",
      RouteUID: "TNN1215",
      RouteID: "1215",
      RouteName: {
        Zh_tw: "藍15",
        En: "B15",
      },
      SubRouteUID: "TNN121511",
      SubRouteID: "121511",
      SubRouteName: {
        Zh_tw: "藍15 漚汪→佳里站[僅供預約]",
        En: "B15 Ouwang→Jiali Bus Station[Reservation only]",
      },
      Direction: 0,
      StopUID: "TNN24781",
      StopID: "24781",
      StopName: {
        Zh_tw: "本善寺",
        En: "Benshan Temple",
      },
      StopSequence: 14,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 99,
      A2EventType: 0,
      GPSTime: "2025-12-18T16:11:39+08:00",
      TripStartTimeType: 2,
      TransTime: "2025-12-18T16:11:39+08:00",
      SrcRecTime: "2025-12-18T16:11:39+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "TDT-6872",
      OperatorID: "16202",
      OperatorNo: "",
      RouteUID: "TNN1229",
      RouteID: "1229",
      RouteName: {
        Zh_tw: "藍29",
        En: "B29",
      },
      SubRouteUID: "TNN122902",
      SubRouteID: "122902",
      SubRouteName: {
        Zh_tw: "藍29 奇美佳里分院→西港",
        En: "B29 Chi Mei Jiali Hospital→Sigang",
      },
      Direction: 1,
      StopUID: "TNN25642",
      StopID: "25642",
      StopName: {
        Zh_tw: "金砂下宅子",
        En: "Jinsha Xiazhaizi",
      },
      StopSequence: 6,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 99,
      A2EventType: 0,
      GPSTime: "2025-12-18T16:13:52+08:00",
      TripStartTimeType: 1,
      TripStartTime: "2025-12-18T15:55:50+08:00",
      TransTime: "2025-12-18T16:13:53+08:00",
      SrcRecTime: "2025-12-18T16:13:53+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "TDY-8126",
      OperatorID: "16202",
      OperatorNo: "",
      RouteUID: "TNN1214",
      RouteID: "1214",
      RouteName: {
        Zh_tw: "藍14",
        En: "B14",
      },
      SubRouteUID: "TNN121402",
      SubRouteID: "121402",
      SubRouteName: {
        Zh_tw: "藍14 奇美佳里分院→學甲區公所",
        En: "B14 Chi Mei Jiali Hospital→Syuejia District Office",
      },
      Direction: 1,
      StopUID: "TNN24765",
      StopID: "24765",
      StopName: {
        Zh_tw: "將軍里(三吉)",
        En: "Jiangjyun Vil.(Sanji)",
      },
      StopSequence: 8,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 0,
      A2EventType: 0,
      GPSTime: "2025-12-18T16:12:41+08:00",
      TripStartTimeType: 0,
      TripStartTime: "2025-12-18T16:00:32+08:00",
      TransTime: "2025-12-18T16:12:43+08:00",
      SrcRecTime: "2025-12-18T16:12:43+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "TDY-8158",
      OperatorID: "16202",
      OperatorNo: "",
      RouteUID: "TNN1215",
      RouteID: "1215",
      RouteName: {
        Zh_tw: "藍15",
        En: "B15",
      },
      SubRouteUID: "TNN121512",
      SubRouteID: "121512",
      SubRouteName: {
        Zh_tw: "藍15 佳里站→漚汪[僅供預約]",
        En: "B15 Jiali Bus Station→Ouwang[Reservation only]",
      },
      Direction: 1,
      StopUID: "TNN24797",
      StopID: "24797",
      StopName: {
        Zh_tw: "謝子寮",
        En: "Siezihliao",
      },
      StopSequence: 13,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 99,
      A2EventType: 0,
      GPSTime: "2025-12-18T15:59:53+08:00",
      TripStartTimeType: 0,
      TripStartTime: "2025-12-18T15:40:02+08:00",
      TransTime: "2025-12-18T15:59:55+08:00",
      SrcRecTime: "2025-12-18T15:59:55+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
    {
      PlateNumb: "TEA-8579",
      OperatorID: "16253",
      OperatorNo: "",
      RouteUID: "TNN1230",
      RouteID: "1230",
      RouteName: {
        Zh_tw: "藍30",
        En: "B30",
      },
      SubRouteUID: "TNN123001",
      SubRouteID: "123001",
      SubRouteName: {
        Zh_tw: "藍30 西港→佳里",
        En: "B30 Sigang→Jiali Bus Station",
      },
      Direction: 0,
      StopUID: "TNN31020",
      StopID: "31020",
      StopName: {
        Zh_tw: "南勢",
        En: "Nanshih",
      },
      StopSequence: 14,
      MessageType: 2,
      DutyStatus: 1,
      BusStatus: 0,
      A2EventType: 0,
      GPSTime: "2025-12-18T16:06:21+08:00",
      TripStartTimeType: 1,
      TripStartTime: "2025-12-18T15:38:52+08:00",
      TransTime: "2025-12-18T16:06:22+08:00",
      SrcRecTime: "2025-12-18T16:06:22+08:00",
      SrcUpdateTime: "2025-12-18T16:14:06+08:00",
      UpdateTime: "2025-12-18T16:14:06+08:00",
    },
  ];

  const subRouteCity = {
    VersionID: 8528,
    UpdateTime: "2025-12-18T00:00:00+08:00",
    UpdateInterval: 14400,
    SrcUpdateTime: "2025-12-18T01:05:06+08:00",
    SrcUpdateInterval: 86400,
    AuthorityCode: "TNN",
    SubRoutes: [
      {
        RouteUID: "TNN10019",
        RouteID: "10019",
        RouteName: {
          Zh_tw: "19",
          En: "19",
        },
        SubRouteUID: "TNN100190",
        SubRouteID: "100190",
        SubRouteName: {
          Zh_tw: "19路 安平→大灣",
          En: "19 AnPing→Dawan",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "16303",
            OperatorName: {
              Zh_tw: "巨業交通(台南)",
              En: "Geya Bus Transport Co., Ltd.",
            },
            OperatorCode: "GeyaBus",
            OperatorNo: "0504",
          },
        ],
        Direction: 0,
        DepartureStopName: {
          Zh_tw: "原住民文化會館",
          En: "The Indigenous Culture Museum",
        },
        DestinationStopName: {
          Zh_tw: "大灣高中",
          En: "Dawan Senior High School",
        },
        StartStop: {
          StopID: "16064",
          StopName: {
            Zh_tw: "原住民文化會館",
            En: "The Indigenous Culture Museum",
          },
        },
        EndStop: {
          StopID: "16107",
          StopName: {
            Zh_tw: "大灣高中",
            En: "Dawan Senior High School",
          },
        },
      },
      {
        RouteUID: "TNN10019",
        RouteID: "10019",
        RouteName: {
          Zh_tw: "19",
          En: "19",
        },
        SubRouteUID: "TNN100197",
        SubRouteID: "100197",
        SubRouteName: {
          Zh_tw: "19路 大灣→臺南海事 [延駛]",
          En: "19 Dawan→National Tainan Senior Marine Fishery Vocational School",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "16303",
            OperatorName: {
              Zh_tw: "巨業交通(台南)",
              En: "Geya Bus Transport Co., Ltd.",
            },
            OperatorCode: "GeyaBus",
            OperatorNo: "0504",
          },
        ],
        Direction: 1,
        DepartureStopName: {
          Zh_tw: "大灣高中",
          En: "Dawan Senior High School",
        },
        DestinationStopName: {
          Zh_tw: "臺南海事",
          En: "National Tainan Senior Marine Fishery Vocational S",
        },
        StartStop: {
          StopID: "16108",
          StopName: {
            Zh_tw: "大灣高中",
            En: "Dawan Senior High School",
          },
        },
        EndStop: {
          StopID: "16940",
          StopName: {
            Zh_tw: "臺南海事",
            En: "National Tainan Senior Marine Fishery Vocational School",
          },
        },
      },
      {
        RouteUID: "TNN10019",
        RouteID: "10019",
        RouteName: {
          Zh_tw: "19",
          En: "19",
        },
        SubRouteUID: "TNN100196",
        SubRouteID: "100196",
        SubRouteName: {
          Zh_tw: "19路 臺南海事→大灣 [延駛]",
          En: "19 National Tainan Senior Marine Fishery Vocational School→Dawan",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "16303",
            OperatorName: {
              Zh_tw: "巨業交通(台南)",
              En: "Geya Bus Transport Co., Ltd.",
            },
            OperatorCode: "GeyaBus",
            OperatorNo: "0504",
          },
        ],
        Direction: 0,
        DepartureStopName: {
          Zh_tw: "臺南海事",
          En: "National Tainan Senior Marine Fishery Vocational S",
        },
        DestinationStopName: {
          Zh_tw: "大灣高中",
          En: "Dawan Senior High School",
        },
        StartStop: {
          StopID: "16928",
          StopName: {
            Zh_tw: "臺南海事",
            En: "National Tainan Senior Marine Fishery Vocational School",
          },
        },
        EndStop: {
          StopID: "16107",
          StopName: {
            Zh_tw: "大灣高中",
            En: "Dawan Senior High School",
          },
        },
      },
      {
        RouteUID: "TNN10019",
        RouteID: "10019",
        RouteName: {
          Zh_tw: "19",
          En: "19",
        },
        SubRouteUID: "TNN100191",
        SubRouteID: "100191",
        SubRouteName: {
          Zh_tw: "19路 大灣→安平",
          En: "19 Dawan→AnPing",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "16303",
            OperatorName: {
              Zh_tw: "巨業交通(台南)",
              En: "Geya Bus Transport Co., Ltd.",
            },
            OperatorCode: "GeyaBus",
            OperatorNo: "0504",
          },
        ],
        Direction: 1,
        DepartureStopName: {
          Zh_tw: "大灣高中",
          En: "Dawan Senior High School",
        },
        DestinationStopName: {
          Zh_tw: "原住民文化會館",
          En: "The Indigenous Culture Museum",
        },
        StartStop: {
          StopID: "16108",
          StopName: {
            Zh_tw: "大灣高中",
            En: "Dawan Senior High School",
          },
        },
        EndStop: {
          StopID: "16151",
          StopName: {
            Zh_tw: "原住民文化會館",
            En: "The Indigenous Culture Museum",
          },
        },
      },
      {
        RouteUID: "TNN10021",
        RouteID: "10021",
        RouteName: {
          Zh_tw: "21",
          En: "21",
        },
        SubRouteUID: "TNN100210",
        SubRouteID: "100210",
        SubRouteName: {
          Zh_tw: "21路 臺南火車站→永康工業區",
          En: "21 Tainan Train Station→Yongkang Industrial Park",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "10001",
            OperatorName: {
              Zh_tw: "府城客運",
              En: "Tainan City Bus",
            },
            OperatorCode: "TainanCityBus",
            OperatorNo: "0803",
          },
        ],
        Direction: 0,
        DepartureStopName: {
          Zh_tw: "臺南火車站(南站)",
          En: "Tainan Train Station(South)",
        },
        DestinationStopName: {
          Zh_tw: "永康休閒育樂中心",
          En: "Yongkang Recreation Center",
        },
        StartStop: {
          StopID: "8755",
          StopName: {
            Zh_tw: "臺南火車站(南站)",
            En: "Tainan Train Station(South Station)",
          },
        },
        EndStop: {
          StopID: "16233",
          StopName: {
            Zh_tw: "永康休閒育樂中心",
            En: "Yongkang Recreation Center",
          },
        },
      },
      {
        RouteUID: "TNN10021",
        RouteID: "10021",
        RouteName: {
          Zh_tw: "21",
          En: "21",
        },
        SubRouteUID: "TNN100211",
        SubRouteID: "100211",
        SubRouteName: {
          Zh_tw: "21路 永康工業區→臺南火車站",
          En: "21 Yongkang Industrial Park→Tainan Train Station",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "10001",
            OperatorName: {
              Zh_tw: "府城客運",
              En: "Tainan City Bus",
            },
            OperatorCode: "TainanCityBus",
            OperatorNo: "0803",
          },
        ],
        Direction: 1,
        DepartureStopName: {
          Zh_tw: "永康休閒育樂中心",
          En: "Yongkang Recreation Center",
        },
        DestinationStopName: {
          Zh_tw: "臺南火車站(南站)",
          En: "Tainan Train Station(South)",
        },
        StartStop: {
          StopID: "16234",
          StopName: {
            Zh_tw: "永康休閒育樂中心",
            En: "Yongkang Recreation Center",
          },
        },
        EndStop: {
          StopID: "8810",
          StopName: {
            Zh_tw: "臺南火車站(南站)",
            En: "Tainan Train Station(South Station)",
          },
        },
      },
      {
        RouteUID: "TNN10021",
        RouteID: "10021",
        RouteName: {
          Zh_tw: "21",
          En: "21",
        },
        SubRouteUID: "TNN100212",
        SubRouteID: "100212",
        SubRouteName: {
          Zh_tw: "21路 9人小巴 臺南火車站→永康工業區(繞奇美醫院)",
          En: "21 Shuttle Taxi Tainan Train Station→Yongkang Industrial Park(Via Chi Mei Medical Center)",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "16273",
            OperatorName: {
              Zh_tw: "府城小黃",
              En: "Tainan City Bus(Shuttle)",
            },
            OperatorCode: "TainanCityBus(Shuttl",
          },
        ],
        Direction: 0,
        DepartureStopName: {
          Zh_tw: "臺南火車站(南站)",
          En: "Tainan Train Station(South)",
        },
        DestinationStopName: {
          Zh_tw: "永康休閒育樂中心",
          En: "Yongkang Recreation Center",
        },
        StartStop: {
          StopID: "8755",
          StopName: {
            Zh_tw: "臺南火車站(南站)",
            En: "Tainan Train Station(South Station)",
          },
        },
        EndStop: {
          StopID: "16233",
          StopName: {
            Zh_tw: "永康休閒育樂中心",
            En: "Yongkang Recreation Center",
          },
        },
      },
      {
        RouteUID: "TNN10021",
        RouteID: "10021",
        RouteName: {
          Zh_tw: "21",
          En: "21",
        },
        SubRouteUID: "TNN100213",
        SubRouteID: "100213",
        SubRouteName: {
          Zh_tw: "21路 9人小巴  永康工業區→臺南火車站(繞奇美醫院)",
          En: "21 Shuttle Taxi Yongkang Industrial Park→Tainan Train Station(Via Chi Mei Medical Center)",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "16273",
            OperatorName: {
              Zh_tw: "府城小黃",
              En: "Tainan City Bus(Shuttle)",
            },
            OperatorCode: "TainanCityBus(Shuttl",
          },
        ],
        Direction: 1,
        DepartureStopName: {
          Zh_tw: "永康休閒育樂中心",
          En: "Yongkang Recreation Center",
        },
        DestinationStopName: {
          Zh_tw: "臺南火車站(南站)",
          En: "Tainan Train Station(South)",
        },
        StartStop: {
          StopID: "16234",
          StopName: {
            Zh_tw: "永康休閒育樂中心",
            En: "Yongkang Recreation Center",
          },
        },
        EndStop: {
          StopID: "8810",
          StopName: {
            Zh_tw: "臺南火車站(南站)",
            En: "Tainan Train Station(South Station)",
          },
        },
      },
      {
        RouteUID: "TNN1009",
        RouteID: "1009",
        RouteName: {
          Zh_tw: "9",
          En: "9",
        },
        SubRouteUID: "TNN100914",
        SubRouteID: "100914",
        SubRouteName: {
          Zh_tw: "9路 9人小巴 東溪埔寮福安宮→臺南轉運站(繞公親里)",
          En: "9 Shuttle Taxi Dongsipuliao Fuan Temple→Tainan Bus Station(Via Gongcin Village)",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "16323",
            OperatorName: {
              Zh_tw: "統聯客運(小巴)",
              En: "Ubus",
            },
            OperatorCode: "UnitedHighwayBus",
            OperatorNo: "1201",
          },
        ],
        Direction: 1,
        DepartureStopName: {
          Zh_tw: "東溪埔寮福安宮",
          En: "Dongsipuliao Fuan Temple",
        },
        DestinationStopName: {
          Zh_tw: "臺南轉運站",
          En: "Tainan Bus Station",
        },
        StartStop: {
          StopID: "31164",
          StopName: {
            Zh_tw: "東溪埔寮福安宮",
            En: "Dongsipuliao Fuan Temple",
          },
        },
        EndStop: {
          StopID: "31111",
          StopName: {
            Zh_tw: "臺南轉運站",
            En: "Tainan Bus Station",
          },
        },
      },
      {
        RouteUID: "TNN1009",
        RouteID: "1009",
        RouteName: {
          Zh_tw: "9",
          En: "9",
        },
        SubRouteUID: "TNN100912",
        SubRouteID: "100912",
        SubRouteName: {
          Zh_tw: "9路 9人小巴 東溪埔寮福安宮→臺南轉運站",
          En: "9 Shuttle Taxi Dongsipuliao Fuan Temple→Tainan Bus Station",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "16323",
            OperatorName: {
              Zh_tw: "統聯客運(小巴)",
              En: "Ubus",
            },
            OperatorCode: "UnitedHighwayBus",
            OperatorNo: "1201",
          },
        ],
        Direction: 1,
        DepartureStopName: {
          Zh_tw: "東溪埔寮福安宮",
          En: "Dongsipuliao Fuan Temple",
        },
        DestinationStopName: {
          Zh_tw: "臺南轉運站",
          En: "Tainan Bus Station",
        },
        StartStop: {
          StopID: "31164",
          StopName: {
            Zh_tw: "東溪埔寮福安宮",
            En: "Dongsipuliao Fuan Temple",
          },
        },
        EndStop: {
          StopID: "31111",
          StopName: {
            Zh_tw: "臺南轉運站",
            En: "Tainan Bus Station",
          },
        },
      },
      {
        RouteUID: "TNN1009",
        RouteID: "1009",
        RouteName: {
          Zh_tw: "9",
          En: "9",
        },
        SubRouteUID: "TNN100902",
        SubRouteID: "100902",
        SubRouteName: {
          Zh_tw: "9路 東溪埔寮福安宮→臺南轉運站",
          En: "9 Dongsipuliao Fuan Temple→Tainan Bus Station",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "16201",
            OperatorName: {
              Zh_tw: "統聯客運(台南)",
              En: "Ubus",
            },
            OperatorCode: "UnitedHighwayBus",
            OperatorNo: "1201",
          },
        ],
        Direction: 1,
        DepartureStopName: {
          Zh_tw: "東溪埔寮福安宮",
          En: "Dongsipuliao Fuan Temple",
        },
        DestinationStopName: {
          Zh_tw: "臺南轉運站",
          En: "Tainan Bus Station",
        },
        StartStop: {
          StopID: "31164",
          StopName: {
            Zh_tw: "東溪埔寮福安宮",
            En: "Dongsipuliao Fuan Temple",
          },
        },
        EndStop: {
          StopID: "31111",
          StopName: {
            Zh_tw: "臺南轉運站",
            En: "Tainan Bus Station",
          },
        },
      },
      {
        RouteUID: "TNN1009",
        RouteID: "1009",
        RouteName: {
          Zh_tw: "9",
          En: "9",
        },
        SubRouteUID: "TNN100913",
        SubRouteID: "100913",
        SubRouteName: {
          Zh_tw: "9路 9人小巴 臺南轉運站→東溪埔寮福安宮(繞公親里)",
          En: "9 Shuttle Taxi Tainan Bus Station→Dongsipuliao Fuan Temple(Via Gongcin Village)",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "16323",
            OperatorName: {
              Zh_tw: "統聯客運(小巴)",
              En: "Ubus",
            },
            OperatorCode: "UnitedHighwayBus",
            OperatorNo: "1201",
          },
        ],
        Direction: 0,
        DepartureStopName: {
          Zh_tw: "臺南轉運站",
          En: "Tainan Bus Station",
        },
        DestinationStopName: {
          Zh_tw: "東溪埔寮福安宮",
          En: "Dongsipuliao Fuan Temple",
        },
        StartStop: {
          StopID: "31046",
          StopName: {
            Zh_tw: "臺南轉運站",
            En: "Tainan Bus Station",
          },
        },
        EndStop: {
          StopID: "31163",
          StopName: {
            Zh_tw: "東溪埔寮福安宮",
            En: "Dongsipuliao Fuan Temple",
          },
        },
      },
      {
        RouteUID: "TNN1009",
        RouteID: "1009",
        RouteName: {
          Zh_tw: "9",
          En: "9",
        },
        SubRouteUID: "TNN100911",
        SubRouteID: "100911",
        SubRouteName: {
          Zh_tw: "9路 9人小巴 臺南轉運站→東溪埔寮福安宮",
          En: "9 Shuttle Taxi Tainan Bus Station→Dongsipuliao Fuan Temple",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "16323",
            OperatorName: {
              Zh_tw: "統聯客運(小巴)",
              En: "Ubus",
            },
            OperatorCode: "UnitedHighwayBus",
            OperatorNo: "1201",
          },
        ],
        Direction: 0,
        DepartureStopName: {
          Zh_tw: "臺南轉運站",
          En: "Tainan Bus Station",
        },
        DestinationStopName: {
          Zh_tw: "東溪埔寮福安宮",
          En: "Dongsipuliao Fuan Temple",
        },
        StartStop: {
          StopID: "31046",
          StopName: {
            Zh_tw: "臺南轉運站",
            En: "Tainan Bus Station",
          },
        },
        EndStop: {
          StopID: "31163",
          StopName: {
            Zh_tw: "東溪埔寮福安宮",
            En: "Dongsipuliao Fuan Temple",
          },
        },
      },
      {
        RouteUID: "TNN1009",
        RouteID: "1009",
        RouteName: {
          Zh_tw: "9",
          En: "9",
        },
        SubRouteUID: "TNN100916",
        SubRouteID: "100916",
        SubRouteName: {
          Zh_tw: "9路 東溪埔寮福安宮→臺南轉運站(繞公親里)",
          En: "9 Dongsipuliao Fuan Temple→Tainan Bus Station(Via Gongcin Village)",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "16201",
            OperatorName: {
              Zh_tw: "統聯客運(台南)",
              En: "Ubus",
            },
            OperatorCode: "UnitedHighwayBus",
            OperatorNo: "1201",
          },
        ],
        Direction: 1,
        DepartureStopName: {
          Zh_tw: "東溪埔寮福安宮",
          En: "Dongsipuliao Fuan Temple",
        },
        DestinationStopName: {
          Zh_tw: "臺南轉運站",
          En: "Tainan Bus Station",
        },
        StartStop: {
          StopID: "31164",
          StopName: {
            Zh_tw: "東溪埔寮福安宮",
            En: "Dongsipuliao Fuan Temple",
          },
        },
        EndStop: {
          StopID: "31111",
          StopName: {
            Zh_tw: "臺南轉運站",
            En: "Tainan Bus Station",
          },
        },
      },
      {
        RouteUID: "TNN1009",
        RouteID: "1009",
        RouteName: {
          Zh_tw: "9",
          En: "9",
        },
        SubRouteUID: "TNN100915",
        SubRouteID: "100915",
        SubRouteName: {
          Zh_tw: "9路 臺南轉運站→東溪埔寮福安宮(繞公親里)",
          En: "9 Tainan Bus Station→Dongsipuliao Fuan Temple(Via Gongcin Village)",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "16201",
            OperatorName: {
              Zh_tw: "統聯客運(台南)",
              En: "Ubus",
            },
            OperatorCode: "UnitedHighwayBus",
            OperatorNo: "1201",
          },
        ],
        Direction: 0,
        DepartureStopName: {
          Zh_tw: "臺南轉運站",
          En: "Tainan Bus Station",
        },
        DestinationStopName: {
          Zh_tw: "東溪埔寮福安宮",
          En: "Dongsipuliao Fuan Temple",
        },
        StartStop: {
          StopID: "31046",
          StopName: {
            Zh_tw: "臺南轉運站",
            En: "Tainan Bus Station",
          },
        },
        EndStop: {
          StopID: "31163",
          StopName: {
            Zh_tw: "東溪埔寮福安宮",
            En: "Dongsipuliao Fuan Temple",
          },
        },
      },
      {
        RouteUID: "TNN1009",
        RouteID: "1009",
        RouteName: {
          Zh_tw: "9",
          En: "9",
        },
        SubRouteUID: "TNN100901",
        SubRouteID: "100901",
        SubRouteName: {
          Zh_tw: "9路 臺南轉運站→東溪埔寮福安宮",
          En: "9 Tainan Bus Station→Dongsipuliao Fuan Temple",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "16201",
            OperatorName: {
              Zh_tw: "統聯客運(台南)",
              En: "Ubus",
            },
            OperatorCode: "UnitedHighwayBus",
            OperatorNo: "1201",
          },
        ],
        Direction: 0,
        DepartureStopName: {
          Zh_tw: "臺南轉運站",
          En: "Tainan Bus Station",
        },
        DestinationStopName: {
          Zh_tw: "東溪埔寮福安宮",
          En: "Dongsipuliao Fuan Temple",
        },
        StartStop: {
          StopID: "31046",
          StopName: {
            Zh_tw: "臺南轉運站",
            En: "Tainan Bus Station",
          },
        },
        EndStop: {
          StopID: "31163",
          StopName: {
            Zh_tw: "東溪埔寮福安宮",
            En: "Dongsipuliao Fuan Temple",
          },
        },
      },
      {
        RouteUID: "TNN1010",
        RouteID: "1010",
        RouteName: {
          Zh_tw: "10",
          En: "10",
        },
        SubRouteUID: "TNN101001",
        SubRouteID: "101001",
        SubRouteName: {
          Zh_tw: "10路 臺南轉運站→鹿耳門天后宮",
          En: "10 Tainan Bus Station→Luermen-Ma Temple",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "16201",
            OperatorName: {
              Zh_tw: "統聯客運(台南)",
              En: "Ubus",
            },
            OperatorCode: "UnitedHighwayBus",
            OperatorNo: "1201",
          },
        ],
        Direction: 0,
        DepartureStopName: {
          Zh_tw: "臺南轉運站",
          En: "Tainan Bus Station",
        },
        DestinationStopName: {
          Zh_tw: "鹿耳門天后宮",
          En: "Luermen-Ma Temple",
        },
        StartStop: {
          StopID: "32359",
          StopName: {
            Zh_tw: "臺南轉運站",
            En: "Tainan Bus Station",
          },
        },
        EndStop: {
          StopID: "32294",
          StopName: {
            Zh_tw: "鹿耳門天后宮",
            En: "Luermen Matsu Temple",
          },
        },
      },
      {
        RouteUID: "TNN1010",
        RouteID: "1010",
        RouteName: {
          Zh_tw: "10",
          En: "10",
        },
        SubRouteUID: "TNN101002",
        SubRouteID: "101002",
        SubRouteName: {
          Zh_tw: "10路 鹿耳門天后宮→臺南轉運站",
          En: "10 Luermen-Ma Temple→Tainan Bus Station",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "16201",
            OperatorName: {
              Zh_tw: "統聯客運(台南)",
              En: "Ubus",
            },
            OperatorCode: "UnitedHighwayBus",
            OperatorNo: "1201",
          },
        ],
        Direction: 1,
        DepartureStopName: {
          Zh_tw: "鹿耳門天后宮",
          En: "Luermen-Ma Temple",
        },
        DestinationStopName: {
          Zh_tw: "臺南轉運站",
          En: "Tainan Train Station(North)",
        },
        StartStop: {
          StopID: "32295",
          StopName: {
            Zh_tw: "鹿耳門天后宮",
            En: "Luermen Matsu Temple",
          },
        },
        EndStop: {
          StopID: "32360",
          StopName: {
            Zh_tw: "臺南轉運站",
            En: "Tainan Bus Station",
          },
        },
      },
      {
        RouteUID: "TNN10161",
        RouteID: "10161",
        RouteName: {
          Zh_tw: "18",
          En: "18",
        },
        SubRouteUID: "TNN101612",
        SubRouteID: "101612",
        SubRouteName: {
          Zh_tw: "18路 大成國中→和順轉運站",
          En: "18 Da-Cheng Junior High School→Heshun Bus Station",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "10001",
            OperatorName: {
              Zh_tw: "府城客運",
              En: "Tainan City Bus",
            },
            OperatorCode: "TainanCityBus",
            OperatorNo: "0803",
          },
        ],
        Direction: 0,
        DepartureStopName: {
          Zh_tw: "大成國中",
          En: "Da-Cheng Junior High School",
        },
        DestinationStopName: {
          Zh_tw: "和順轉運站",
          En: "Heshun Bus Station",
        },
        StartStop: {
          StopID: "22425",
          StopName: {
            Zh_tw: "大成國中",
            En: "Da-Cheng Junior High School",
          },
        },
        EndStop: {
          StopID: "31369",
          StopName: {
            Zh_tw: "和順轉運站",
            En: "Heshun Bus Station",
          },
        },
      },
      {
        RouteUID: "TNN10161",
        RouteID: "10161",
        RouteName: {
          Zh_tw: "18",
          En: "18",
        },
        SubRouteUID: "TNN101761",
        SubRouteID: "101761",
        SubRouteName: {
          Zh_tw: "18路 和順轉運站→大成國中 [繞北安路]",
          En: "18 Heshun Bus Station→Da-Cheng Junior High School[Via Beian Rd.]",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "10001",
            OperatorName: {
              Zh_tw: "府城客運",
              En: "Tainan City Bus",
            },
            OperatorCode: "TainanCityBus",
            OperatorNo: "0803",
          },
        ],
        Direction: 1,
        DepartureStopName: {
          Zh_tw: "和順轉運站",
          En: "Heshun Bus Station",
        },
        DestinationStopName: {
          Zh_tw: "大成國中",
          En: "Da-Cheng Junior High School",
        },
        StartStop: {
          StopID: "31370",
          StopName: {
            Zh_tw: "和順轉運站",
            En: "Heshun Bus Station",
          },
        },
        EndStop: {
          StopID: "22426",
          StopName: {
            Zh_tw: "大成國中",
            En: "Da-Cheng Junior High School",
          },
        },
      },
      {
        RouteUID: "TNN10161",
        RouteID: "10161",
        RouteName: {
          Zh_tw: "18",
          En: "18",
        },
        SubRouteUID: "TNN101618",
        SubRouteID: "101618",
        SubRouteName: {
          Zh_tw: "18路 大成國中→和順轉運站 [延國民路]",
          En: "18 Da-Cheng Junior High School→Heshun Bus Station[Via Guomin Rd.]",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "10001",
            OperatorName: {
              Zh_tw: "府城客運",
              En: "Tainan City Bus",
            },
            OperatorCode: "TainanCityBus",
            OperatorNo: "0803",
          },
        ],
        Direction: 0,
        DepartureStopName: {
          Zh_tw: "國民路",
          En: "Guomin Rd.",
        },
        DestinationStopName: {
          Zh_tw: "和順轉運站",
          En: "Heshun Bus Station",
        },
        StartStop: {
          StopID: "8914",
          StopName: {
            Zh_tw: "國民路",
            En: "Guomin Rd.",
          },
        },
        EndStop: {
          StopID: "31369",
          StopName: {
            Zh_tw: "和順轉運站",
            En: "Heshun Bus Station",
          },
        },
      },
      {
        RouteUID: "TNN10161",
        RouteID: "10161",
        RouteName: {
          Zh_tw: "18",
          En: "18",
        },
        SubRouteUID: "TNN101619",
        SubRouteID: "101619",
        SubRouteName: {
          Zh_tw: "18路 和順轉運站→大成國中 [延國民路]",
          En: "18 Heshun Bus Station→Simen Rd. ＆ Da-Cheng Junior High School[Via Guomin Rd.]",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "10001",
            OperatorName: {
              Zh_tw: "府城客運",
              En: "Tainan City Bus",
            },
            OperatorCode: "TainanCityBus",
            OperatorNo: "0803",
          },
        ],
        Direction: 1,
        DepartureStopName: {
          Zh_tw: "和順轉運站",
          En: "Heshun Bus Station",
        },
        DestinationStopName: {
          Zh_tw: "國民路",
          En: "Guomin Rd.",
        },
        StartStop: {
          StopID: "31370",
          StopName: {
            Zh_tw: "和順轉運站",
            En: "Heshun Bus Station",
          },
        },
        EndStop: {
          StopID: "8919",
          StopName: {
            Zh_tw: "國民路",
            En: "Guomin Rd.",
          },
        },
      },
      {
        RouteUID: "TNN10161",
        RouteID: "10161",
        RouteName: {
          Zh_tw: "18",
          En: "18",
        },
        SubRouteUID: "TNN101613",
        SubRouteID: "101613",
        SubRouteName: {
          Zh_tw: "18路 和順轉運站→大成國中",
          En: "18 Heshun Bus Station→Da-Cheng Junior High School",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "10001",
            OperatorName: {
              Zh_tw: "府城客運",
              En: "Tainan City Bus",
            },
            OperatorCode: "TainanCityBus",
            OperatorNo: "0803",
          },
        ],
        Direction: 1,
        DepartureStopName: {
          Zh_tw: "和順轉運站",
          En: "Heshun Bus Station",
        },
        DestinationStopName: {
          Zh_tw: "大成國中",
          En: "Da-Cheng Junior High School",
        },
        StartStop: {
          StopID: "31370",
          StopName: {
            Zh_tw: "和順轉運站",
            En: "Heshun Bus Station",
          },
        },
        EndStop: {
          StopID: "22426",
          StopName: {
            Zh_tw: "大成國中",
            En: "Da-Cheng Junior High School",
          },
        },
      },
      {
        RouteUID: "TNN10161",
        RouteID: "10161",
        RouteName: {
          Zh_tw: "18",
          En: "18",
        },
        SubRouteUID: "TNN101760",
        SubRouteID: "101760",
        SubRouteName: {
          Zh_tw: "18路 大成國中→和順轉運站 [繞北安路]",
          En: "18 Da-Cheng Junior High School→Heshun Bus Station[Via Beian Rd.]",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "10001",
            OperatorName: {
              Zh_tw: "府城客運",
              En: "Tainan City Bus",
            },
            OperatorCode: "TainanCityBus",
            OperatorNo: "0803",
          },
        ],
        Direction: 0,
        DepartureStopName: {
          Zh_tw: "大成國中",
          En: "Da-Cheng Junior High School",
        },
        DestinationStopName: {
          Zh_tw: "和順轉運站",
          En: "Heshun Bus Station",
        },
        StartStop: {
          StopID: "22425",
          StopName: {
            Zh_tw: "大成國中",
            En: "Da-Cheng Junior High School",
          },
        },
        EndStop: {
          StopID: "31369",
          StopName: {
            Zh_tw: "和順轉運站",
            En: "Heshun Bus Station",
          },
        },
      },
      {
        RouteUID: "TNN10162",
        RouteID: "10162",
        RouteName: {
          Zh_tw: "2",
          En: "2",
        },
        SubRouteUID: "TNN101624",
        SubRouteID: "101624",
        SubRouteName: {
          Zh_tw: "2路 白鷺灣社區→崑山科大",
          En: "2 Bailuwan Community→Kun Shan University",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "10001",
            OperatorName: {
              Zh_tw: "府城客運",
              En: "Tainan City Bus",
            },
            OperatorCode: "TainanCityBus",
            OperatorNo: "0803",
          },
        ],
        Direction: 1,
        DepartureStopName: {
          Zh_tw: "白鷺灣社區",
          En: "Bailuwan Community",
        },
        DestinationStopName: {
          Zh_tw: "崑山科大",
          En: "Kun Shan University",
        },
        StartStop: {
          StopID: "14382",
          StopName: {
            Zh_tw: "白鷺灣社區",
            En: "Bailuwan Community",
          },
        },
        EndStop: {
          StopID: "9057",
          StopName: {
            Zh_tw: "崑山科大",
            En: "Kun Shan University of Technology",
          },
        },
      },
      {
        RouteUID: "TNN10162",
        RouteID: "10162",
        RouteName: {
          Zh_tw: "2",
          En: "2",
        },
        SubRouteUID: "TNN101723",
        SubRouteID: "101723",
        SubRouteName: {
          Zh_tw: "2路 三鯤鯓→崑山科大",
          En: "2 Sankunshen→Kun Shan University",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "10001",
            OperatorName: {
              Zh_tw: "府城客運",
              En: "Tainan City Bus",
            },
            OperatorCode: "TainanCityBus",
            OperatorNo: "0803",
          },
        ],
        Direction: 1,
        DepartureStopName: {
          Zh_tw: "三鯤鯓",
          En: "SanKunShen",
        },
        DestinationStopName: {
          Zh_tw: "崑山科大",
          En: "Kun Shan University",
        },
        StartStop: {
          StopID: "10823",
          StopName: {
            Zh_tw: "三鯤鯓",
            En: "SanKunShen",
          },
        },
        EndStop: {
          StopID: "9057",
          StopName: {
            Zh_tw: "崑山科大",
            En: "Kun Shan University of Technology",
          },
        },
      },
      {
        RouteUID: "TNN10162",
        RouteID: "10162",
        RouteName: {
          Zh_tw: "2",
          En: "2",
        },
        SubRouteUID: "TNN101626",
        SubRouteID: "101626",
        SubRouteName: {
          Zh_tw: "2路 崑山科大→四草",
          En: "2 Kun Shan University→Sihcao",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "10001",
            OperatorName: {
              Zh_tw: "府城客運",
              En: "Tainan City Bus",
            },
            OperatorCode: "TainanCityBus",
            OperatorNo: "0803",
          },
        ],
        Direction: 0,
        DepartureStopName: {
          Zh_tw: "崑山科大",
          En: "Kun Shan University",
        },
        DestinationStopName: {
          Zh_tw: "四草",
          En: "Sih-Cao",
        },
        StartStop: {
          StopID: "9001",
          StopName: {
            Zh_tw: "崑山科大",
            En: "Kun Shan University",
          },
        },
        EndStop: {
          StopID: "13979",
          StopName: {
            Zh_tw: "四草",
            En: "Sih-Cao",
          },
        },
      },
      {
        RouteUID: "TNN10162",
        RouteID: "10162",
        RouteName: {
          Zh_tw: "2",
          En: "2",
        },
        SubRouteUID: "TNN101726",
        SubRouteID: "101726",
        SubRouteName: {
          Zh_tw: "2路 崑山科大→白鷺灣社區(經復華里)",
          En: "2 Kun Shan University→Bailuwan Community[Via Fuhua Vil.]",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "10001",
            OperatorName: {
              Zh_tw: "府城客運",
              En: "Tainan City Bus",
            },
            OperatorCode: "TainanCityBus",
            OperatorNo: "0803",
          },
        ],
        Direction: 0,
        DepartureStopName: {
          Zh_tw: "崑山科大",
          En: "Kun Shan University",
        },
        DestinationStopName: {
          Zh_tw: "白鷺灣社區",
          En: "Bailuwan Community",
        },
        StartStop: {
          StopID: "9001",
          StopName: {
            Zh_tw: "崑山科大",
            En: "Kun Shan University",
          },
        },
        EndStop: {
          StopID: "14381",
          StopName: {
            Zh_tw: "白鷺灣社區",
            En: "Bailuwan Community",
          },
        },
      },
      {
        RouteUID: "TNN10162",
        RouteID: "10162",
        RouteName: {
          Zh_tw: "2",
          En: "2",
        },
        SubRouteUID: "TNN101627",
        SubRouteID: "101627",
        SubRouteName: {
          Zh_tw: "2路 四草→崑山科大",
          En: "2 Sihcao→Kun Shan University",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "10001",
            OperatorName: {
              Zh_tw: "府城客運",
              En: "Tainan City Bus",
            },
            OperatorCode: "TainanCityBus",
            OperatorNo: "0803",
          },
        ],
        Direction: 1,
        DepartureStopName: {
          Zh_tw: "四草",
          En: "Sih-Cao",
        },
        DestinationStopName: {
          Zh_tw: "崑山科大",
          En: "Kun Shan University",
        },
        StartStop: {
          StopID: "13990",
          StopName: {
            Zh_tw: "四草",
            En: "Sih-Cao",
          },
        },
        EndStop: {
          StopID: "9057",
          StopName: {
            Zh_tw: "崑山科大",
            En: "Kun Shan University of Technology",
          },
        },
      },
      {
        RouteUID: "TNN10162",
        RouteID: "10162",
        RouteName: {
          Zh_tw: "2",
          En: "2",
        },
        SubRouteUID: "TNN101623",
        SubRouteID: "101623",
        SubRouteName: {
          Zh_tw: "2路 崑山科大→白鷺灣社區",
          En: "2 Kun Shan University→Bailuwan Community",
        },
        SubRouteLongName: {},
        Operators: [
          {
            OperatorID: "10001",
            OperatorName: {
              Zh_tw: "府城客運",
              En: "Tainan City Bus",
            },
            OperatorCode: "TainanCityBus",
            OperatorNo: "0803",
          },
        ],
        Direction: 0,
        DepartureStopName: {
          Zh_tw: "崑山科大",
          En: "Kun Shan University",
        },
        DestinationStopName: {
          Zh_tw: "白鷺灣社區",
          En: "Bailuwan Community",
        },
        StartStop: {
          StopID: "9001",
          StopName: {
            Zh_tw: "崑山科大",
            En: "Kun Shan University",
          },
        },
        EndStop: {
          StopID: "14381",
          StopName: {
            Zh_tw: "白鷺灣社區",
            En: "Bailuwan Community",
          },
        },
      },
    ],
  };
  const maxBodyLengthapNameURL = {
    VersionID: 8528,
    UpdateTime: "2025-12-18T00:00:00+08:00",
    UpdateInterval: 14400,
    SrcUpdateTime: "2025-12-18T01:05:03+08:00",
    SrcUpdateInterval: 86400,
    AuthorityCode: "TNN",
    Stops: [
      {
        StopUID: "TNN10010",
        StopID: "10010",
        StopName: {
          Zh_tw: "西門健康立體停車場",
          En: "Simen Rd. ＆ Jiankang Rd. Parking Tower",
        },
        StopPosition: { PositionLon: 120.19756, PositionLat: 22.98237 },
        Bearing: "S",
        CityCode: "8",
        StopAddress: "台南市南區西門路一段473-499號",
        StationUID: "TNN9284",
        StationID: "9284",
      },
      {
        StopUID: "TNN10014",
        StopID: "10014",
        StopName: { Zh_tw: "塭南里", En: "Wunnan Village" },
        StopPosition: { PositionLon: 120.22081, PositionLat: 23.06983 },
        Bearing: "W",
        CityCode: "8",
        StopAddress: "台南市安南區安昌街174巷79弄21號",
        StationUID: "TNN9299",
        StationID: "9299",
      },
      {
        StopUID: "TNN10015",
        StopID: "10015",
        StopName: {
          Zh_tw: "西門健康立體停車場",
          En: "Simen Rd. ＆ Jiankang Rd. Parking Tower",
        },
        StopPosition: { PositionLon: 120.19769, PositionLat: 22.98216 },
        Bearing: "N",
        CityCode: "8",
        StopAddress: "台南市中西區西門路一段420號",
        StationUID: "TNN9201",
        StationID: "9201",
      },
      {
        StopUID: "TNN10019",
        StopID: "10019",
        StopName: { Zh_tw: "海東國小", En: "Haidong Elementary School" },
        StopPosition: { PositionLon: 120.17543, PositionLat: 23.04892 },
        Bearing: "E",
        CityCode: "8",
        StopAddress: "台南市安南區安中路三段381號",
        StationUID: "TNN344",
        StationID: "344",
      },
      {
        StopUID: "TNN10021",
        StopID: "10021",
        StopName: { Zh_tw: "海東國小", En: "Haidong Elementary School" },
        StopPosition: { PositionLon: 120.17548, PositionLat: 23.04902 },
        Bearing: "W",
        CityCode: "8",
        StopAddress: "台南市安南區安中路三段381號",
        StationUID: "TNN343",
        StationID: "343",
      },
      {
        StopUID: "TNN10022",
        StopID: "10022",
        StopName: { Zh_tw: "鹽行", En: "Yanhang" },
        StopPosition: { PositionLon: 120.23669, PositionLat: 23.04099 },
        RoadName: "中正南路",
        Bearing: "SW",
        CityCode: "8",
        StopAddress: "台南市永康區中正南路785-871號",
        StationUID: "TNN501",
        StationID: "501",
      },
      {
        StopUID: "TNN10023",
        StopID: "10023",
        StopName: {
          Zh_tw: "臺南航空站(奇美幸福工廠)",
          En: "Tainan Airport(CHIMEI Happiness Factory)",
        },
        StopPosition: { PositionLon: 120.21681, PositionLat: 22.94841 },
        Bearing: "N",
        CityCode: "8",
        StopAddress: "台南市南區機場路169號",
        StationUID: "TNN531",
        StationID: "531",
      },
      {
        StopUID: "TNN10024",
        StopID: "10024",
        StopName: { Zh_tw: "鹽行", En: "Yanhang" },
        StopPosition: { PositionLon: 120.23662, PositionLat: 23.04071 },
        RoadName: "中正南路",
        Bearing: "NE",
        CityCode: "8",
        StopAddress: "台南市永康區中正南路728-804號",
        StationUID: "TNN562",
        StationID: "562",
      },
      {
        StopUID: "TNN10025",
        StopID: "10025",
        StopName: { Zh_tw: "裕誠街口", En: "Yucheng St. Intersection" },
        StopPosition: { PositionLon: 120.23957, PositionLat: 22.98783 },
        RoadName: "裕農三街",
        Bearing: "S",
        CityCode: "8",
        StopAddress: "台南市東區裕農三街51號",
        StationUID: "TNN643",
        StationID: "643",
      },
      {
        StopUID: "TNN10026",
        StopID: "10026",
        StopName: { Zh_tw: "新興國宅", En: "Sinsing Public Housing" },
        StopPosition: { PositionLon: 120.18735, PositionLat: 22.96161 },
        Bearing: "E",
        CityCode: "8",
        StopAddress: "台南市南區中華南路二段306號",
        StationUID: "TNN606",
        StationID: "606",
      },
      {
        StopUID: "TNN10027",
        StopID: "10027",
        StopName: { Zh_tw: "龍崗國小", En: "LongGang Elementary School" },
        StopPosition: { PositionLon: 120.16962, PositionLat: 22.96158 },
        RoadName: "鯤鯓路",
        Bearing: "S",
        CityCode: "8",
        StopAddress: "台南市南區鯤鯓路147號",
        StationUID: "TNN600",
        StationID: "600",
      },
      {
        StopUID: "TNN10028",
        StopID: "10028",
        StopName: { Zh_tw: "裕誠街口", En: "Yucheng St. Intersection" },
        StopPosition: { PositionLon: 120.23958, PositionLat: 22.98794 },
        RoadName: "裕農三街",
        Bearing: "N",
        CityCode: "8",
        StopAddress: "台南市東區裕農三街51號",
        StationUID: "TNN642",
        StationID: "642",
      },
      {
        StopUID: "TNN10029",
        StopID: "10029",
        StopName: {
          Zh_tw: "臺南火車站(南站)",
          En: "Tainan Train Station(South Station)",
        },
        StopPosition: { PositionLon: 120.21127, PositionLat: 22.99709 },
        Bearing: "SE",
        CityCode: "8",
        StopAddress: "台南市北區成功路1-7號",
        StationUID: "TNN9211",
        StationID: "9211",
      },
      {
        StopUID: "TNN10030",
        StopID: "10030",
        StopName: { Zh_tw: "台糖安南學苑", En: "An-nan Institute" },
        StopPosition: { PositionLon: 120.15253, PositionLat: 23.05751 },
        RoadName: "育英街",
        Bearing: "NE",
        CityCode: "8",
        StopAddress: "台南市安南區育英街",
        StationUID: "TNN734",
        StationID: "734",
      },
      {
        StopUID: "TNN10031",
        StopID: "10031",
        StopName: {
          Zh_tw: "臺南火車站(北站)",
          En: "Tainan Train Station(North Station)",
        },
        StopPosition: { PositionLon: 120.21151, PositionLat: 22.99766 },
        Bearing: "SW",
        CityCode: "8",
        StopAddress: "台南市北區成功路2號",
        StationUID: "TNN9274",
        StationID: "9274",
      },
      {
        StopUID: "TNN10134",
        StopID: "10134",
        StopName: { Zh_tw: "西門路一段", En: "Sec. 1 Si-Men Road" },
        StopPosition: { PositionLon: 120.19766, PositionLat: 22.98421 },
        Bearing: "N",
        CityCode: "8",
        StopAddress: "台南市西門路一段498號",
        StationUID: "TNN9202",
        StationID: "9202",
      },
      {
        StopUID: "TNN10135",
        StopID: "10135",
        StopName: {
          Zh_tw: "新光三越新天地",
          En: "Shinkong Mitsukoshi Department Store",
        },
        StopPosition: { PositionLon: 120.19764, PositionLat: 22.98711 },
        Bearing: "N",
        CityCode: "8",
        StopAddress: "台南市中西區西門路一段658號新光三越台南新天地店",
        StationUID: "TNN9203",
        StationID: "9203",
      },
      {
        StopUID: "TNN10136",
        StopID: "10136",
        StopName: { Zh_tw: "小西門(西門路)", En: "Siaosimen(Simen Rd.)" },
        StopPosition: { PositionLon: 120.19761, PositionLat: 22.98881 },
        Bearing: "N",
        CityCode: "8",
        StopAddress: "台南市中西區西門路一段668號",
        StationUID: "TNN9281",
        StationID: "9281",
      },
      {
        StopUID: "TNN10137",
        StopID: "10137",
        StopName: { Zh_tw: "西門、友愛街口", En: "Simen Rd.＆Youai St." },
        StopPosition: { PositionLon: 120.19817, PositionLat: 22.99113 },
        RoadName: "西門路二段",
        Bearing: "N",
        CityCode: "8",
        StopAddress: "台南市中西區西門路二段28號",
        StationUID: "TNN9205",
        StationID: "9205",
      },
      {
        StopUID: "TNN10138",
        StopID: "10138",
        StopName: { Zh_tw: "西門、民權路口", En: "Simen Rd.＆ Mincyuan Rd." },
        StopPosition: { PositionLon: 120.19942, PositionLat: 22.99511 },
        Bearing: "N",
        CityCode: "8",
        StopAddress: "台南市中西區西門路二段214號",
        StationUID: "TNN9206",
        StationID: "9206",
      },
      {
        StopUID: "TNN10139",
        StopID: "10139",
        StopName: {
          Zh_tw: "西門路三段口",
          En: "Sec. 3 Si-Men Road Intersection",
        },
        StopPosition: { PositionLon: 120.20101, PositionLat: 22.99912 },
        RoadName: "西門路二段",
        Bearing: "NE",
        CityCode: "8",
        StopAddress: "台南市中西區西門路二段404號",
        StationUID: "TNN9207",
        StationID: "9207",
      },
      {
        StopUID: "TNN10140",
        StopID: "10140",
        StopName: { Zh_tw: "成功國小", En: "Cheng-Gong Elementary School" },
        StopPosition: { PositionLon: 120.20275, PositionLat: 22.99908 },
        RoadName: "成功路",
        Bearing: "E",
        CityCode: "8",
        StopAddress: "台南市中西區成功路237號",
        StationUID: "TNN9208",
        StationID: "9208",
      },
      {
        StopUID: "TNN10141",
        StopID: "10141",
        StopName: { Zh_tw: "鴨母寮市場", En: "Yamuliao Traditional Market" },
        StopPosition: { PositionLon: 120.20453, PositionLat: 22.99849 },
        RoadName: "成功路",
        Bearing: "E",
        CityCode: "8",
        StopAddress: "台南市中西區成功路213號",
        StationUID: "TNN9209",
        StationID: "9209",
      },
      {
        StopUID: "TNN10142",
        StopID: "10142",
        StopName: { Zh_tw: "大道公廟", En: "Dadaogong Temple" },
        StopPosition: { PositionLon: 120.20619, PositionLat: 22.99816 },
        Bearing: "E",
        CityCode: "8",
        StopAddress: "台南市中西區觀亭街110號",
        StationUID: "TNN9210",
        StationID: "9210",
      },
      {
        StopUID: "TNN10143",
        StopID: "10143",
        StopName: {
          Zh_tw: "臺南火車站(南站)",
          En: "Tainan Train Station(South Station)",
        },
        StopPosition: { PositionLon: 120.21127, PositionLat: 22.99709 },
        Bearing: "SE",
        CityCode: "8",
        StopAddress: "台南市北區成功路1-7號",
        StationUID: "TNN9211",
        StationID: "9211",
      },
      {
        StopUID: "TNN10144",
        StopID: "10144",
        StopName: { Zh_tw: "公園南路", En: "Gong-Yuan South Road" },
        StopPosition: { PositionLon: 120.21017, PositionLat: 23.00074 },
        RoadName: "公園南路",
        Bearing: "W",
        CityCode: "8",
        StopAddress: "台南市北區公園南路77-91號",
        StationUID: "TNN9212",
        StationID: "9212",
      },
      {
        StopUID: "TNN10145",
        StopID: "10145",
        StopName: { Zh_tw: "臺南轉運站", En: "Tainan Bus Station" },
        StopPosition: { PositionLon: 120.20928, PositionLat: 23.00187 },
        Bearing: "NE",
        CityCode: "8",
        StopAddress: "台南市北區公園路287號",
        StationUID: "TNN9213",
        StationID: "9213",
      },
      {
        StopUID: "TNN10146",
        StopID: "10146",
        StopName: { Zh_tw: "寮內", En: "Liaonei" },
        StopPosition: { PositionLon: 120.21036, PositionLat: 23.00588 },
        Bearing: "N",
        CityCode: "8",
        StopAddress: "台南市北區公園路516巷18號",
        StationUID: "TNN9214",
        StationID: "9214",
      },
      {
        StopUID: "TNN10147",
        StopID: "10147",
        StopName: { Zh_tw: "延平國中", En: "Yenping Junior High School" },
        StopPosition: { PositionLon: 120.21077, PositionLat: 23.01028 },
        RoadName: "公園路",
        Bearing: "N",
        CityCode: "8",
        StopAddress: "台南市北區公園路557號",
        StationUID: "TNN9215",
        StationID: "9215",
      },
      {
        StopUID: "TNN10148",
        StopID: "10148",
        StopName: {
          Zh_tw: "延平市場(長榮路)",
          En: "Yanping Market(Changrong Rd.)",
        },
        StopPosition: { PositionLon: 120.21327, PositionLat: 23.01321 },
        Bearing: "W",
        CityCode: "8",
        StopAddress: "台南市北區長榮路五段462-482號",
        StationUID: "TNN9216",
        StationID: "9216",
      },
    ],
  };

  return { network, realTimeNearStop, maxBodyLengthapNameURL, subRouteCity };
}

export { fetchTainanBusNetwork };
